### ISSUE TITLE
Clustering example requires more iterations

### ISSUE THREAD

**Issue by nclarkjudd** [BGU-CS-VIL/dpmmpython#2]
Hi there,

On my hardware and with no attempt whatsoever to configure Julia, PyJulia, or how this software uses the underlying solvers, the DPGMM performs poorly in the [clustering example](https://github.com/BGU-CS-VIL/dpmmpython/blob/master/examples/clustering_example.ipynb) at only 500 iterations.

Setting n_iter to 1,000 significantly improves its performance (near to the level of performance advertised, and superior to both K-Means and scikit-learn's GMM).

I recall seeing somewhere in the documentation for this package a recommendation to tune how `openblas` is called, maybe that is why. Either way, it may be better to either adjust n_iter in that example notebook, or emphasize any necessary tuning prior to using the package.

**Comment by dinarior** [comment]
Hi,

Performance do you mean the clustering result (e.g. the NMI score) or the duration? For the former, there is some randomness involved (mainly in the data generation), GMM and K-MEANS sometimes converge faster, especially when the data is relatively easy  (solving a simpler model), or when the DPGMM suffers from bad initialization, in addition, the example used the default burnout rate (20), which slows convergence quite a bit, but is safer to use to get more stable results, however, 20 is a bit of an overkill for 2d data. I will modify the example a bit. 

Was the timing bad as well? If so what Julia version are you using?
the `openblas` modification is useful when working with multiprocess, which used to be the only option, but now if no additional processes are created (this can be done by `addprocs` from python) it will exploit the multithreaded capabilities of `BLAS`, thus no need to reduce the number of `BLAS` threads.

**Comment by dinarior** [comment]
I have modified the notebook, reducing the `burnout` to `10` and fixing Julia's random seed (to 1) for the data generation.

There are of course cases where the GMM and K-MEANS will still outperform the DPGMM, but in most cases I have tested the DPGMM outperformed the others. If that is not true for you please let me know.

**Comment by nclarkjudd** [comment]
Thanks for your prompt response.

The issue was with the clustering result --- the NMI score at 500 iterations was roughly .33 on the first run. Increasing the number of iterations to 1000 solved this issue for that set of simulated data and one or two subsequent runs.

I am investigating this package for an application in social science and am interested in optimizing for model fit rather than convergence speed.

Using %timeit your modified notebook produces model results in 7.5s +/- 125ms on my machine, an Intel Core i9-9900K at its stock speed (3.6 GHz). That seems fine to me.

After modifying burnout and setting the seed, I reproduce exactly the results rendered in the notebook (as expected).

Changing the seed, I still get comparable results where the DPGMM's NMI score > GMM > KMeans.

Perhaps the issue was initialization but it could also have been simulated data with highly overlapping clusters. I would imagine a greater burn-in and a greater number of iterations would help in either case, no? I would be interested in your view on this because in my own application the clusters will overlap in one or two of about 10 dimensions. 

I am also concerned about label switching but I believe that initializing the DPGMM with priors from a DPGMM estimated using variational approximation should minimize that risk. 

The independence assumptions that come with variational approximation are problematic in my case. My hope is that your implementation will lead to better inferences about posterior distributions of parameters, where with variational approximation the MAP estimates seem to be really all one can work with.

**Comment by dinarior** [comment]
Hi,

We have observed that behaviour, where bad initialization prevents the model from creating new clusters, in two different scenarios:

- Crowded overlapping clusters.
- Unbalanced clusters (For example, a cluster with 99% of the data and another with 1%).

When the above happens, it's due to two subclusters that are stuck in a local maximum, thus increasing the number of iterations could solve it due to the probabilistic nature of the MCMC process. Increasing the burn-in will not help in this case, as the burn-in is used to prevent premature splitting of clusters, which is not the case. I have found that setting the burn-in to 15 usually works best in my use cases, which are mostly higher-dimensional data, in the tradeoff between stability and convergence speed.

Having said that, we have observed the bad initialization problem in lower dimensions, where `D<=3`. We have tried to reproduce it on higher dimensions but failed, and very rarely we see it occurring in "real" higher dimensional data - which is often due to choosing a bad prior **_and_** having bad initialization.

If your working with `10D` data, I think you should be fine, even if in many of the dimensions you have clusters overlapping each other.

If running time is not a problem, I would also suggest using some cluster-fusion technique, which is used to merge multiple runs into a single one. When one of the runs suffers from bad initialization it mitigates it.
I have used my takeoff on [this paper](https://link.springer.com/chapter/10.1007/3-540-46014-4_21), which works quite well. I could supply you with the code if needed, I think I have it in Julia, but should be easy to translate into Python. This should also help you with the label switching, as it matches the clusters between the different runs with each other, creating a consistent result.

Heres the code: https://gist.github.com/dinarior/a214b260cb34ccd1402ab1c93ec65b14

**Comment by nclarkjudd** [comment]
Thanks very much!
